name: omnibase
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pip
  - pip:
      - pyserial
      - scipy
      - matplotlib
      - aiohttp==3.8.4
      - aioice==0.9.0
      - aiortc==1.5.0
      - aiosignal==1.3.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - av==10.0.0
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - cryptography==40.0.2
      - dnspython==2.3.0
      - frozenlist==1.3.3
      - google-crc32c==1.5.0
      - idna==3.4
      - ifaddr==0.2.0
      - multidict==6.0.4
      - numpy==1.24.3
      - opencv-python==4.7.0.72
      - pycparser==2.21
      - pyee==9.1.0
      - pylibsrtp==0.8.0
      - pyOpenSSL==23.1.1
      - typing_extensions==4.5.0
      - yarl==1.9.2